package main

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/url"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"

	"github.com/coder/websocket"
)

type createTunnelResponse struct {
	TunnelID   string `json:"tunnel_id"`
	Token      string `json:"token"`
	ClientPath string `json:"client_path"`
	Target     string `json:"target"`
	ExpiresAt  string `json:"expires_at"`
	Error      string `json:"error"`
}

type tunnelTicket struct {
	Server     string `json:"server"`
	ClientPath string `json:"client_path"`
	Token      string `json:"token"`
}

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, "chat-codex-tunnel:", err)
		os.Exit(1)
	}
}

func run(args []string) error {
	if len(args) == 0 || args[0] != "connect" {
		return errors.New("usage: chat-codex-tunnel connect --machine MACHINE_ID")
	}
	flags := flag.NewFlagSet("connect", flag.ContinueOnError)
	machineID := flags.String("machine", "", "device machine id")
	server := flags.String("server", strings.TrimRight(strings.TrimSpace(os.Getenv("CHAT_CODEX_PUBLIC_BASE")), "/"), "Chat Codex public base URL")
	accessToken := flags.String("access-token", strings.TrimSpace(os.Getenv("CHAT_CODEX_ACCESS_TOKEN")), "access token; prefer CHAT_CODEX_ACCESS_TOKEN")
	ticketValue := flags.String("ticket", "", "short-lived tunnel ticket generated by Launcher")
	if err := flags.Parse(args[1:]); err != nil {
		return err
	}
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()
	if strings.TrimSpace(*ticketValue) != "" {
		ticket, err := decodeTunnelTicket(*ticketValue)
		if err != nil {
			return err
		}
		return connectTunnel(ctx, ticket.Server, ticket.ClientPath, ticket.Token)
	}
	if strings.TrimSpace(*machineID) == "" {
		return errors.New("--machine is required")
	}
	if strings.TrimSpace(*server) == "" {
		return errors.New("--server or CHAT_CODEX_PUBLIC_BASE is required")
	}
	if strings.TrimSpace(*accessToken) == "" {
		return errors.New("--access-token or CHAT_CODEX_ACCESS_TOKEN is required")
	}
	response, err := createTunnel(ctx, strings.TrimRight(strings.TrimSpace(*server), "/"), *machineID, *accessToken)
	if err != nil {
		return err
	}
	return connectTunnel(ctx, *server, response.ClientPath, response.Token)
}

func decodeTunnelTicket(value string) (tunnelTicket, error) {
	data, err := base64.RawURLEncoding.DecodeString(strings.TrimSpace(value))
	if err != nil {
		return tunnelTicket{}, errors.New("invalid tunnel ticket")
	}
	var ticket tunnelTicket
	if err := json.Unmarshal(data, &ticket); err != nil {
		return tunnelTicket{}, errors.New("invalid tunnel ticket")
	}
	if strings.TrimSpace(ticket.Server) == "" || strings.TrimSpace(ticket.ClientPath) == "" || strings.TrimSpace(ticket.Token) == "" {
		return tunnelTicket{}, errors.New("incomplete tunnel ticket")
	}
	return ticket, nil
}

func connectTunnel(ctx context.Context, server, clientPath, token string) error {
	tunnelURL, err := tunnelWebSocketURL(server, clientPath, token)
	if err != nil {
		return err
	}
	dialCtx, cancel := context.WithTimeout(ctx, 15*time.Second)
	conn, _, err := websocket.Dial(dialCtx, tunnelURL, nil)
	cancel()
	if err != nil {
		return fmt.Errorf("connect tunnel: %w", err)
	}
	defer conn.CloseNow()
	stream := websocket.NetConn(ctx, conn, websocket.MessageBinary)
	defer stream.Close()
	return bridge(ctx, os.Stdin, os.Stdout, stream)
}

func createTunnel(ctx context.Context, server, machineID, accessToken string) (createTunnelResponse, error) {
	body, err := json.Marshal(map[string]string{"machine_id": machineID})
	if err != nil {
		return createTunnelResponse{}, err
	}
	request, err := http.NewRequestWithContext(ctx, http.MethodPost,
		server+"/api/devices/"+url.PathEscape(machineID)+"/tunnels", strings.NewReader(string(body)))
	if err != nil {
		return createTunnelResponse{}, err
	}
	request.Header.Set("Authorization", "Bearer "+accessToken)
	request.Header.Set("Content-Type", "application/json")
	response, err := http.DefaultClient.Do(request)
	if err != nil {
		return createTunnelResponse{}, err
	}
	defer response.Body.Close()
	var payload createTunnelResponse
	if err := json.NewDecoder(response.Body).Decode(&payload); err != nil {
		return createTunnelResponse{}, fmt.Errorf("decode create response: %w", err)
	}
	if response.StatusCode/100 != 2 {
		if payload.Error == "" {
			payload.Error = response.Status
		}
		return createTunnelResponse{}, errors.New(payload.Error)
	}
	if payload.Token == "" || payload.ClientPath == "" {
		return createTunnelResponse{}, errors.New("server returned incomplete tunnel credentials")
	}
	return payload, nil
}

func tunnelWebSocketURL(server, path, token string) (string, error) {
	base, err := url.Parse(strings.TrimSpace(server))
	if err != nil || base.Host == "" {
		return "", errors.New("invalid server URL")
	}
	if base.Scheme == "https" {
		base.Scheme = "wss"
	} else if base.Scheme == "http" {
		base.Scheme = "ws"
	}
	parsed, err := url.Parse(path)
	if err != nil {
		return "", err
	}
	prefix := strings.TrimSuffix(base.Path, "/")
	base.Path = strings.TrimRight(prefix, "/") + "/" + strings.TrimLeft(parsed.Path, "/")
	base.RawPath = ""
	query := base.Query()
	query.Set("token", token)
	base.RawQuery = query.Encode()
	return base.String(), nil
}

func bridge(ctx context.Context, input io.Reader, output io.Writer, stream netConn) error {
	type result struct {
		direction string
		err       error
	}
	results := make(chan result, 2)
	go func() { _, err := io.Copy(stream, input); results <- result{direction: "ssh-to-tunnel", err: err} }()
	go func() { _, err := io.Copy(output, stream); results <- result{direction: "tunnel-to-ssh", err: err} }()
	select {
	case <-ctx.Done():
		return ctx.Err()
	case result := <-results:
		if result.err != nil && !errors.Is(result.err, net.ErrClosed) {
			return fmt.Errorf("%s: %w", result.direction, result.err)
		}
		fmt.Fprintf(os.Stderr, "chat-codex-tunnel: %s closed\n", result.direction)
		return nil
	}
}

type netConn interface {
	io.Reader
	io.Writer
	io.Closer
}
