// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplySelfUpdate() {
  return window['go']['main']['GUIApp']['ApplySelfUpdate']();
}

export function AutostartStatus() {
  return window['go']['main']['GUIApp']['AutostartStatus']();
}

export function CheckSelfUpdate() {
  return window['go']['main']['GUIApp']['CheckSelfUpdate']();
}

export function ClearSavedLogin() {
  return window['go']['main']['GUIApp']['ClearSavedLogin']();
}

export function CreateAgent(arg1) {
  return window['go']['main']['GUIApp']['CreateAgent'](arg1);
}

export function CreateSSHTunnel() {
  return window['go']['main']['GUIApp']['CreateSSHTunnel']();
}

export function Defaults() {
  return window['go']['main']['GUIApp']['Defaults']();
}

export function Directories(arg1) {
  return window['go']['main']['GUIApp']['Directories'](arg1);
}

export function DirectoryPermission(arg1) {
  return window['go']['main']['GUIApp']['DirectoryPermission'](arg1);
}

export function InstallSSHAuthorizedKey(arg1) {
  return window['go']['main']['GUIApp']['InstallSSHAuthorizedKey'](arg1);
}

export function LoadSavedLogin() {
  return window['go']['main']['GUIApp']['LoadSavedLogin']();
}

export function Login(arg1) {
  return window['go']['main']['GUIApp']['Login'](arg1);
}

export function MCPStatus(arg1) {
  return window['go']['main']['GUIApp']['MCPStatus'](arg1);
}

export function PrepareRuntimeEnvironment() {
  return window['go']['main']['GUIApp']['PrepareRuntimeEnvironment']();
}

export function RemoveAgent(arg1) {
  return window['go']['main']['GUIApp']['RemoveAgent'](arg1);
}

export function RestartAgent(arg1) {
  return window['go']['main']['GUIApp']['RestartAgent'](arg1);
}

export function RestartBackground() {
  return window['go']['main']['GUIApp']['RestartBackground']();
}

export function RuntimeEnvironment() {
  return window['go']['main']['GUIApp']['RuntimeEnvironment']();
}

export function SSHStatus() {
  return window['go']['main']['GUIApp']['SSHStatus']();
}

export function SaveSavedLogin(arg1) {
  return window['go']['main']['GUIApp']['SaveSavedLogin'](arg1);
}

export function SetAgentEnabled(arg1) {
  return window['go']['main']['GUIApp']['SetAgentEnabled'](arg1);
}

export function SetAutostart(arg1) {
  return window['go']['main']['GUIApp']['SetAutostart'](arg1);
}

export function SetTerminalCompatEnabled(arg1) {
  return window['go']['main']['GUIApp']['SetTerminalCompatEnabled'](arg1);
}

export function SetupSSH() {
  return window['go']['main']['GUIApp']['SetupSSH']();
}

export function StartLauncher() {
  return window['go']['main']['GUIApp']['StartLauncher']();
}

export function State() {
  return window['go']['main']['GUIApp']['State']();
}

export function TerminalCompatSettings() {
  return window['go']['main']['GUIApp']['TerminalCompatSettings']();
}
