// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {main} from '../models';

export function ApplySelfUpdate():Promise<model.LauncherSelfUpdateResult>;

export function AutostartStatus():Promise<model.LauncherAutostartInfo>;

export function CheckSelfUpdate():Promise<model.LauncherSelfUpdateResult>;

export function ClearSavedLogin():Promise<void>;

export function CreateAgent(arg1:model.CreateAgentInput):Promise<model.Agent>;

export function CreateSSHTunnel():Promise<main.SSHTunnelResult>;

export function Defaults():Promise<Record<string, any>>;

export function Directories(arg1:model.DirectoryRequest):Promise<model.DirectoryListResult>;

export function DirectoryPermission(arg1:model.DirectoryPermissionInput):Promise<model.DirectoryPermissionResult>;

export function InstallSSHAuthorizedKey(arg1:string):Promise<model.SSHAuthorizedKeyResult>;

export function LoadSavedLogin():Promise<main.SavedLogin>;

export function Login(arg1:main.LoginInput):Promise<main.LoginResult>;

export function MCPStatus(arg1:string):Promise<model.MCPStatusInfo>;

export function PrepareRuntimeEnvironment():Promise<model.RuntimeEnvironmentInfo>;

export function RemoveAgent(arg1:string):Promise<void>;

export function RestartAgent(arg1:string):Promise<model.Agent>;

export function RestartBackground():Promise<main.BootstrapResult>;

export function RuntimeEnvironment():Promise<model.RuntimeEnvironmentInfo>;

export function SSHStatus():Promise<model.SSHStatus>;

export function SaveSavedLogin(arg1:main.SavedLogin):Promise<void>;

export function SetAgentEnabled(arg1:model.SetAgentEnabledInput):Promise<model.Agent>;

export function SetAutostart(arg1:boolean):Promise<model.LauncherAutostartInfo>;

export function SetTerminalCompatEnabled(arg1:boolean):Promise<main.GUISettings>;

export function SetupSSH():Promise<model.SSHSetupResult>;

export function StartLauncher():Promise<main.BootstrapResult>;

export function State():Promise<main.BootstrapResult>;

export function TerminalCompatSettings():Promise<main.GUISettings>;
